name: typesearch
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_background: ^1.2.0
  flutter_webrtc: ^0.9.48+hotfix.1
  http: ^1.2.0
  permission_handler: ^11.3.0
  sdp_transform: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
